ALTER TABLE pedido
  MODIFY COLUMN estado ENUM(
    'PENDIENTE',
    'APROBADO',
    'APROBADO_MANUAL',
    'CANCELADO',
    'CANCELADO_MANUAL',
    'ERROR_STOCK',
    'REQUIERE_ATENCION'
  ) NOT NULL DEFAULT 'PENDIENTE';
