ALTER TABLE pedido
  MODIFY COLUMN estado ENUM(
    'PENDIENTE',
    'APROBADO',
    'APROBADO_MANUAL',
    'CANCELADO',
    'CANCELADO_MANUAL',
    'ERROR_STOCK',
    'RECUPERACION_PENDIENTE'
  ) NOT NULL DEFAULT 'PENDIENTE';
